### ISSUE TITLE
Reorganize the repo

### ISSUE THREAD

**Issue by nwu63** [mdolab/pygeo#81]
# Description
There are several unnecessarily large files in this repo:
- `DVConstraints.py` has 6468 lines
- `DVGeometry.py` has 4541 lines
- `geo_utils.py` has 4509 lines

We should move some code into new files. For example, we should have separate files for separate constraint and DV classes instead of having them all in the same file. These files can be stored in separate directories.

**Comment by akleb** [comment]
Possibly consider #85 as well

**Comment by marcomangano** [comment]
> Possibly consider #85 as well

Yeah I was about to link that issue here but you anticipated me. This should definitely part of the refactoring.
I have to be honest, my understanding in how imports are handled at package level is limited, but I am pretty sure we need to change the way `__init__.py` handles them. @nwu63 do you know how to address this?

**Comment by nwu63** [comment]
Step one would be to identify which modules require MPI, and which ones can optionally use MPI. From there on, there are two options that I see:
- Remove all init imports, and force everyone to use the full path. This is not as user-friendly but very explicit
- If only a small number of functions within the module require MPI, it's possible to import MPI in there (I think) while leaving the top level imports intact. We will have to investigate whether this approach works though.

We can of course also use a mixed strategy, where the basic, fundamental modules (which presumably don't depend on MPI) are provided via the init, while others have to be imported via the full path.


From a very quick glance, this is what I see:
- `DVConstraints.py`: dependence is minimal, other than print statements it's only used by geograd, so can embed in specific functions
- `DVGeometry.py`: again, super minimal
- `DVGeometryESP.py`: hard dependency
- `DVGeometryVSP.py`: hard dependency

**Comment by kanekosh** [comment]
> Remove all init imports, and force everyone to use the full path. This is not as user-friendly but very explicit

This will impact so many scripts (not just the pygeo code), I'm not sure if it is worth doing it.

> If only a small number of functions within the module require MPI, it's possible to import MPI in there (I think) while leaving the top level imports intact. We will have to investigate whether this approach works though.

@akleb has a similar fix on pyfoil side (see #85 ) and that seems simpler than doing the fix in pygeo. 

Has this MPI import been an issue for many people (or will it be)? If so we should probably fix in pygeo side, but otherwise I'd suggest going with the pyfoil's fix.

**Comment by akleb** [comment]
I thought if `pygeo` was already being refactored than the backward compatibility would already be broken, making it easier to slip in the refactor for the `mpi4py` issues. However, it seems like this is more of an internal refactoring rather than a public api refactor. I don't think #85 is important enough to warrant a backward incompatible change, but if backwards compatibility was already broken then I think the fix should be tacked on.

**Comment by nwu63** [comment]
I just commented on #85. In general I think it's a bad idea to import `mpi4py` because as you can see, it causes unintended consequences. Therefore, I am happy to break backwards compatibility (minimally, since this should only affect people who use things like the OpenVSP wrapper) in order to fix this.

**Comment by kanekosh** [comment]
Note from a call:
- We'll first reorganize the repo/split files in a backward compatibility manner (by keep importing all the classes/modules we currently import in `pygeo/__init__`). Preserve the git history if possible.
- After that, we'll discuss with other people in the lab and hopefully make backward-incompatible changes so that the MPI import issue is resolved.
